general:
  environment: Production
  serverPort: 3000
  clientUrl: https://coffee-dsw.scilifelab.se
  secret: "aSecretString"
  serviceToken: "aRandomString"
  integrationConfig: "engine-wizard/config/integration.yml"

database:
  host: dsw-mongo
  databaseName: dsw-test
  port: 27017
  authEnabled: true
  username: mongoadmin
  password: mongopassword

messaging:
  host: dsw-rabbit
  port: 5672
  username: rabbit
  password: rabbitpassword
  vhost: dsw-test

mail:
  enabled: false
  name:
  email:
  host:
  port:
  ssl:
  authEnabled:
  username:
  password:

analytics:
  enabled: false
  email:
