---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: menu-aggregator
  namespace: coffee-menu
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"
spec:
  tls:
  - hosts:
    - coffee-menu.dckube.scilifelab.se
    secretName: menu-aggregator-tls
  rules:
    - host: coffee-menu.dckube.scilifelab.se
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: menu-aggregator
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: menu-aggregator
                port:
                  number: 80
