---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: coffee-dsw-mongo
    type: dev
  name: coffee-dsw-mongo
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/storage/coffee-dsw-mongo
    server: 192.168.81.133

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dsw-mongo-storage
  labels:
    storage: dsw-mongo
    type: dev
  namespace: coffee-dsw
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
    limits:
      storage: 10Gi
  selector:
    matchLabels:
      storage: coffee-dsw-mongo
  storageClassName: ''
