---
apiVersion: v1
kind: Pod
metadata:
  name: menu-frontend
  labels:
    id: menu-frontend
spec:
  containers:
    - name: menu-frontend
      image: scilifelabdatacentre/menu-frontend:latest
      ports:
        - containerPort: 80
