---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: menu-rs
spec:
  selector:
    matchLabels:
      name: menu-frontend
      type: rs
  replicas: 5
  template:
    metadata:
      labels:
        name: menu-frontend
        type: rs
        version: a
    spec:
      containers:
        - name: menu-frontend
          image: scilifelabdatacentre/menu-frontend:latest
          ports:
            - containerPort: 80
