---
apiVersion: v1
kind: Service
metadata:
  name: menu-aggregator
  labels:
    name: menu-aggregator
spec:
  ports:
    - name: backend
      port: 8000
      targetPort: 8000
  selector:
    id: menu-backend
