---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    name: db-data
    storage: db-data
  name: coffee-db-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/storage/coffee
    server: 192.168.81.133

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  labels:
    storage: db-data
  namespace: lostb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
    limits:
      storage: 10Gi
  selector:
    matchLabels:
      storage: coffee-db-data
  storageClassName: ''
